document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\" />");
document.writeln("    <title>尾部模块</title>");
document.writeln("    <link rel=\"stylesheet\" href=\" css/foot.css\" />");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <footer>");
document.writeln("        <div class=\"footer_detail\">");
document.writeln("            <div class=\"footer_detail_top\">");
document.writeln("                <div class=\"footer_detail_top_left\">");
document.writeln("                    <p>合作伙伴</p>");
document.writeln("                    <div class=\"footer_detail_top_left_icon\">");
document.writeln("                        <img src=\" images/hf/parternerLogo_01.png\">");
document.writeln("                        <img src=\" images/hf/parternerLogo_02.png\">");
document.writeln("                        <img src=\" images/hf/parternerLogo_03.png\">");
document.writeln("                        <img src=\" images/hf/parternerLogo_04.png\">");
document.writeln("                        <img src=\" images/hf/parternerLogo_05.png\">");
document.writeln("                        <span>更多</span>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\"footer_detail_top_right\">");
document.writeln("                    <p>易臻云旗下平台微信公众号</p>");
document.writeln("                    <div class=\"footer_detail_top_right_icon\">");
document.writeln("                        <img src=\" images/hf/QRCode_CONBA (1).jpg\">");
document.writeln("                        <img src=\" images/hf/QRCode_CONBA (2).jpg\">");
document.writeln("                        <img src=\" images/hf/QRCode_CONBA.jpg\">");
document.writeln("                    </div>");
document.writeln("                    <p class=\"right_item\">");
document.writeln("                        <span>易臻云视界中心</span><span>浙医四院易臻云药房</span><span>易臻云康恩贝</span>");
document.writeln("                    </p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <hr>");
document.writeln("            <div class=\"footer_detail_bottom\">");
document.writeln("                <div class=\"bottom_left\">");
document.writeln("                    <img src=\" images/hf/e-care_logo.png\">");
document.writeln("                </div>");
document.writeln("                <div class=\"bottom_middle\">");
document.writeln("                    <span>关于我们</span><span>|</span>");
document.writeln("                    <span>加入我们</span><span>|</span>");
document.writeln("                    <span>下载app</span><span>|</span>");
document.writeln("                    <span>隐私政策</span>");
document.writeln("                </div>");
document.writeln("                <div class=\"bottom_right\">");
document.writeln("                    <span>服务电话：4009260916</span>");
document.writeln("                    <span>公司地址：杭州市西湖区西园四路2号浙大创新院</span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"icp\"><span>©浙江易臻云医院管理有限公司&nbsp;|&nbsp;浙ICP备16014009号</span></div>");
document.writeln("    </footer>");
document.writeln("    <script src=\" js/jquery.js\"></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");