document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\" />");
document.writeln("    <title>尾部模块</title>");
document.writeln("    <link rel=\"stylesheet\" href=\" css/head.css\" />");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <header>");
document.writeln("        <nav>");
document.writeln("            <div class=\"logo\">");
document.writeln("                <img src=\" images/hf/e-care_logo.png\">");
document.writeln("            </div>");
document.writeln("            <ul class=\"list\">");
document.writeln("                <li>");
document.writeln("                    <a href=\"\">首页</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\">易臻云介绍</a>");
document.writeln("                </li>");
document.writeln("                <li class=\"drug_mes\">");
document.writeln("                    <a href=\"\">药品信息服务</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\">合作伙伴</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\">联系我们</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\"\">登陆/注册</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <div class=\"logo_r\">");
document.writeln("                <img src=\" images/hf/icon_more.png\">");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("        <ul class=\"mes\">");
document.writeln("            <li>");
document.writeln("                <a href=\"\">招标信息</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">招商信息</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">药品信息</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <ul class=\"tab_c\">");
document.writeln("            <li>");
document.writeln("                <a href=\"\">首页</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">易臻云介绍</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">药品信息服务</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">合作伙伴</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">联系我们</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\"\">登陆/注册</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </header>");
document.writeln("    <script src=\" js/jquery.js\"></script>");
document.writeln("    <script src=\" js/headswitch.js\"></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");